version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://miguelteranj02:jew502LCt4ARIDCN@cluster0.jj3kl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 
    volumes:
      - ./backend:/usr/src/app
    command: pnpm start
